package cli

import "fmt"

// scaffoldGoMod returns the go.mod for a scaffolded project.
func scaffoldGoMod(module string) string {
	return fmt.Sprintf(`module %s

go 1.25

require github.com/brandonbert8/grove v%s
`, module, Version)
}

// scaffoldMain returns main.go for a scaffolded project, importing the
// hello module through the project's own module path.
func scaffoldMain(module string) string {
	return fmt.Sprintf(`package main

import (
	grove "github.com/brandonbert8/grove/packages/core"
	"github.com/brandonbert8/grove/packages/middleware"

	"%s/modules/hello"
)

// This file was generated by `+"`grove new`"+`. It wires the stock
// middleware chain (Recovery outermost, then RequestID + Logging) and
// the example hello module with a /healthz probe.

func main() {
	app := grove.New()
	app.Router.Use(
		middleware.Recovery(app.Logger),
		middleware.RequestID(),
		middleware.Logging(app.Logger),
	)

	app.MustRegister(
		hello.Module.AsModule(),
		grove.HealthModule("").AsModule(),
	)

	if err := app.Run(""); err != nil {
		panic(err)
	}
}
`, module)
}

// scaffoldHelloModule returns the example module wiring.
func scaffoldHelloModule() string {
	return `// Package hello is an example Grove module.
package hello

import (
	grove "github.com/brandonbert8/grove/packages/core"
	"github.com/brandonbert8/grove/packages/di"
)

// Module wires the hello service and controller.
var Module = &grove.ModuleDef{
	Name: "hello",
	Providers: []grove.Provider{
		grove.Provide0(di.Singleton, NewService),
	},
	BuildControllers: func(app *grove.App) ([]grove.ControllerDef, error) {
		svc, err := di.ResolveAs[*Service](app.Container)
		if err != nil {
			return nil, err
		}
		h := NewHandler(svc)
		return []grove.ControllerDef{{
			Prefix: "/hello",
			Endpoints: []grove.Endpoint{
				// Empty path mounts exactly at the prefix: GET /hello.
				grove.GET("", h.Greet),
			},
		}}, nil
	},
}
`
}

// scaffoldHelloService returns the example service.
func scaffoldHelloService() string {
	return `package hello

// Service holds hello business logic.
type Service struct{ message string }

// NewService builds the hello Service.
func NewService() *Service { return &Service{message: "Hello Grove"} }

// Message returns the greeting.
func (s *Service) Message() string { return s.message }
`
}

// scaffoldHelloHandler returns the example handler.
func scaffoldHelloHandler() string {
	return `package hello

import "github.com/brandonbert8/grove/packages/router"

// Handler serves hello routes.
type Handler struct{ svc *Service }

// NewHandler builds a Handler.
func NewHandler(svc *Service) *Handler { return &Handler{svc: svc} }

// Greet answers GET /hello.
func (h *Handler) Greet(c router.Context) error {
	return c.JSON(200, map[string]string{"message": h.svc.Message()})
}
`
}
