package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/brandonbert8/grove/packages/cli/ui"
)

// ExistsError reports a taken destination. Commands map it to an
// actionable block (choose another name or --force).
type ExistsError struct {
	Path string
}

// Error implements error.
func (e *ExistsError) Error() string {
	return fmt.Sprintf("directory %s already exists", e.Path)
}

// Scaffold creates a minimal Grove project returning every file written
// as CREATE changes (sorted, stable output).
//
// name accepts three shapes (like `go` tooling):
//   - plain "myapp" → dir parent/myapp, module "myapp";
//   - module path "github.com/foo/bar" → dir parent/bar, module "github.com/foo/bar";
//   - absolute "/tmp/myapp" → dir as given, module "myapp".
//
// groveVersion is the resolved framework version for go.mod (see
// ResolveGroveVersion). Without force, an existing directory aborts
// with *ExistsError; --force replaces it.
func Scaffold(parentDir, name string, force bool, groveVersion string) (string, []ui.FileChange, error) {
	base, modPath, err := resolveBase(parentDir, name)
	if err != nil {
		return "", nil, err
	}
	if _, err := os.Stat(base); err == nil {
		if !force {
			return "", nil, &ExistsError{Path: base}
		}
		if err := os.RemoveAll(base); err != nil {
			return "", nil, err
		}
	}
	dirs := []string{
		base,
		filepath.Join(base, "modules", "hello"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return "", nil, err
		}
	}
	modName := filepath.Base(base)
	files := map[string]string{
		"go.mod":                      scaffoldGoMod(modPath, groveVersion),
		"main.go":                     scaffoldMain(modPath),
		".env.example":                "PORT=3000\nLOG_LEVEL=info\n",
		".gitignore":                  ".env\n",
		"modules/hello/module.go":     scaffoldHelloModule(),
		"modules/hello/service.go":    scaffoldHelloService(),
		"modules/hello/controller.go": scaffoldHelloController(),
		"README.md":                   "# " + modName + "\n\nCreated with `grove new " + modName + "`.\n\nRun with `go run .`.\n",
	}
	changes, err := writeFilesCollect(base, files)
	if err != nil {
		return "", nil, err
	}
	return base, rebase(base, changes), nil
}

// resolveBase computes the destination dir and module path without
// touching disk. Commands use it to fail fast (e.g. existing dir)
// before slow steps like version resolution.
func resolveBase(parentDir, name string) (base, modPath string, err error) {
	if strings.TrimSpace(name) == "" {
		return "", "", &UsageError{Msg: "project name must not be empty"}
	}
	if parentDir == "" {
		parentDir, err = os.Getwd()
		if err != nil {
			return "", "", err
		}
	}
	switch {
	case filepath.IsAbs(name):
		base, modPath = name, filepath.Base(name)
	case strings.Contains(name, "/"):
		modPath = strings.TrimSuffix(name, "/")
		base = filepath.Join(parentDir, filepath.Base(modPath))
	default:
		base, modPath = filepath.Join(parentDir, name), name
	}
	if modPath == "" || modPath == "." || modPath == "/" {
		return "", "", &UsageError{Msg: fmt.Sprintf("invalid project name %q", name)}
	}
	return base, modPath, nil
}

// writeFilesCollect writes files, reporting CREATE per new file and SKIP
// per existing one (never overwrites). Keys sort for stable output.
func writeFilesCollect(dir string, files map[string]string) ([]ui.FileChange, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	keys := make([]string, 0, len(files))
	for k := range files {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var out []ui.FileChange
	for _, rel := range keys {
		p := filepath.Join(dir, rel)
		if _, err := os.Stat(p); err == nil {
			out = append(out, ui.FileChange{Action: ui.Skip, Path: rel})
			continue
		}
		if err := os.WriteFile(p, []byte(files[rel]), 0o644); err != nil {
			return nil, err
		}
		out = append(out, ui.FileChange{Action: ui.Create, Path: rel})
	}
	return out, nil
}

// scaffoldGoMod returns the go.mod for a scaffolded project, pinning a
// resolved framework version (see ResolveGroveVersion) — never a tag
// that might not exist.
func scaffoldGoMod(module, groveVersion string) string {
	return fmt.Sprintf(`module %s

go 1.25

require github.com/brandonbert8/grove %s
`, module, groveVersion)
}

// scaffoldMain returns main.go for a scaffolded project, importing the
// hello module through the project's own module path.
func scaffoldMain(module string) string {
	return fmt.Sprintf(`package main

import (
	grove "github.com/brandonbert8/grove/packages/core"
	"github.com/brandonbert8/grove/packages/middleware"

	"%s/modules/hello"
	// grove:imports
)

// This file was generated by `+"`grove new`"+`. It wires the stock
// middleware chain and the example hello module with a /healthz probe.

func main() {
	app := grove.New()
	app.Router.Use(middleware.DefaultChain(app.Logger)...)
	// NestJS-style globals (the APP_GUARD / APP_INTERCEPTOR equivalent):
	// app.UseGuards(grove.GuardFunc(requireAuth))
	// app.UseInterceptors(grove.WrapData())

	app.MustRegister(
		hello.Module.AsModule(),
		grove.HealthModule("").AsModule(),
		// grove:modules
	)

	if err := app.Listen(); err != nil {
		panic(err)
	}
}
`, module)
}

// scaffoldHelloModule returns the example module wiring.
func scaffoldHelloModule() string {
	return `// Package hello is an example Grove module.
package hello

import (
	grove "github.com/brandonbert8/grove/packages/core"
	"github.com/brandonbert8/grove/packages/di"
)

// Module wires the hello service and controller.
var Module = &grove.ModuleDef{
	Name: "hello",
	Providers: []grove.Provider{
		grove.Provide0(di.Singleton, NewService),
	},
	BuildControllers: func(app *grove.App) ([]grove.ControllerDef, error) {
		return grove.Controllers(app, NewController, func(ctrl *Controller) grove.ControllerDef {
			return grove.ControllerDef{
				Prefix: "/hello",
				Tags:   []string{"hello"},
				Endpoints: []grove.Endpoint{
					// Empty path mounts exactly at the prefix: GET /hello.
					grove.GET("", ctrl.Greet, grove.WithSummary("Greet")),
				},
			}
		})
	},
}
`
}

// scaffoldHelloService returns the example service.
func scaffoldHelloService() string {
	return `package hello

// Service holds hello business logic.
type Service struct{ message string }

// NewService builds the hello Service.
func NewService() *Service { return &Service{message: "Hello Grove"} }

// Message returns the greeting.
func (s *Service) Message() string { return s.message }
`
}

// scaffoldHelloController returns the example controller
// (the @Controller() equivalent for the hello module).
func scaffoldHelloController() string {
	return `package hello

import "github.com/brandonbert8/grove/packages/router"

// Controller serves hello routes.
type Controller struct{ svc *Service }

// NewController builds a Controller with constructor injection.
func NewController(svc *Service) *Controller { return &Controller{svc: svc} }

// Greet answers GET /hello.
func (c *Controller) Greet(ctx router.Context) error {
	return ctx.JSON(200, map[string]string{"message": c.svc.Message()})
}
`
}
